export const SET_GOOGLE_AUTHENTICATED = "SET_GOOGLE_AUTHENTICATED";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";

export const LOAD_SHIFTS_SUCCESS = "LOAD_SHIFTS_SUCCESS";
export const UPDATE_SHIFT_SUCCESS = "UPDATE_SHIFT_SUCCESS";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_STATE = "SET_AUTH_STATE";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
